import React, { useState } from "react";
import { roles } from "../data/roles";
import PageTransition from "../components/layouts/PageTransition";

function MockInterview() {
  const [selectedRole, setSelectedRole] = useState("");

  return (
    <PageTransition>
      <section className="pt-25 md:pt-30 px-4 pb-10 font-rubik min-h-screen">
      <div className="max-w-7xl mx-auto rounded-3xl bg-white/70 backdrop-blur-md shadow-xl border border-white/20 p-6 md:p-10">

        {/* Heading */}
        <div className="text-center">
          <h2 className="text-3xl md:text-5xl font-bold text-gray-800">
            AI Mock Interview
          </h2>

          <p className="mt-4 text-gray-600 max-w-2xl mx-auto">
            Choose your target role and practice realistic interview questions
            generated by AI.
          </p>
        </div>

        {/* Roles */}
        <div className="mt-12">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-xl md:text-2xl font-semibold">
              Select a Role
            </h3>

            <span className="text-sm text-red-500">
              * Required
            </span>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">
            {roles.map((role) => {
              const isSelected = selectedRole === role.id;

              return (
                <button
                  key={role.id}
                  onClick={() => setSelectedRole(role.id)}
                  className={`group relative rounded-2xl border p-5 transition-all duration-300 hover:-translate-y-1 ${
                    isSelected
                      ? "border-cyan-500 bg-cyan-500 text-white shadow-xl"
                      : "border-gray-200 bg-white hover:border-cyan-300 hover:shadow-lg"
                  }`}
                >
                  {isSelected && (
                    <div className="absolute hidden lg:block right-4 top-4 h-6 w-6 items-center justify-center rounded-full bg-white text-cyan-600 font-bold">
                      ✓
                    </div>
                  )}

                  <p className="font-semibold">{role.role}</p>
                </button>
              );
            })}
          </div>
        </div>

        {/* Continue */}
        <div className="mt-10 flex justify-center">
          <button
            disabled={!selectedRole}
            className={`rounded-xl px-10 py-3 font-semibold text-white transition-all duration-300 ${
              selectedRole
                ? "bg-cyan-500 hover:bg-cyan-600 hover:scale-105 shadow-lg cursor-pointer"
                : "bg-gray-300 cursor-not-allowed"
            }`}
          >
            Continue
          </button>
        </div>
      </div>
    </section>
    </PageTransition>
  );
}

export default MockInterview;