import React, { useState } from "react";
import PageTransition from "../components/layouts/PageTransition";
import MockInterview1 from "../components/sections/mockInterview1";
import MockInterview2 from "../components/sections/MockInterview2";
import { useSelector } from "react-redux";
import { AnimatePresence, motion } from "framer-motion";

function MockInterview() {

  const { selectedRole , isContinue1 } = useSelector((state) => state.mockInterview);
 console.log(isContinue1)

  return (
    <PageTransition>
      <section className="pt-23 md:pt-30 px-4 pb-10 font-rubik min-h-screen">
      <div className="max-w-7xl mx-auto rounded-3xl bg-white/70 backdrop-blur-md shadow-xl border border-white/20 p-6 md:p-10">

        {/* Heading */}
        <div className="text-center">
          <h2 className="text-3xl md:text-5xl font-bold text-gray-800">
            AI Mock Interview
          </h2>

          <p className="mt-4 text-gray-600 max-w-2xl mx-auto">
            Choose your target role and practice realistic interview questions
            generated by AI.
          </p>
        </div>

        <AnimatePresence mode="wait">
            {selectedRole && isContinue1 ? (
              <motion.div
                key="interview2"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.4 }}
              >
                <MockInterview2 />
              </motion.div>
            ) : (
              <motion.div
                key="interview1"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.4 }}
              >
                <MockInterview1 />
              </motion.div>
            )}
          </AnimatePresence>

       
      </div>
    </section>
    </PageTransition>
  );
}

export default MockInterview;